id: P9A794458
initial_creation_type: input
source_metadata:
  title: Shechen Gyaltsab Gyurme Pema Namgyal
  language: it
  description: 'Texts by and about Shechen Gyatsab Gyurme Pema Namgyal (zhe chen rgyal
    tshab ''gyur med padma rnam rgyal, 1871–1926):'
  volume:
    e57742e15ec04487b2a7280af3d66d51:
      title: Advice for Gelong Jampa Dargye
      parent: Advice
    592dc03cffe24dd284952e400422cd46:
      title: A Prayer of Aspiration
      parent: Aspiration Prayers
    7d610a11eca6419c98f1e0f69ab3d9b6:
      title: Lamp Aspiration Prayer
      parent: Aspiration Prayers
    43812e2f0a20400e92f2e22d3ffa766f:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    15ad2a35032047ea8e640a1d8645fc80:
      title: Brief Offering Prayer to Gesar
      parent: Dharma Protectors
    2085c917edc24678ac9d113938b0084b:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Dharma Protectors
    3690775eefe74c48ae2565e2d13d1318:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    e4b16495e0704cd5b2b470fa44eb1b65:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    b04918ea570d427798bdfb2b4cffe5d2:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    29ef44adeef84f4c9fc9f1c0db483c71:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    1e1d3d47c1114729a971e27c4a1ea776:
      title: A Prayer To Padmasambhava
      parent: Prayers
    d8c42a70f46e484d8c01cc529212253a:
      title: A Prayer to Amitāyus
      parent: Prayers
    fa8f7e868cde4bf8b3f928af49c0e343:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    852b410adf9a4ed6b8c31ae490541bfd:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Prayers
    bc95c4276f8147cb9b9c5a1f06a53927:
      title: A Concise Feast Prayer
      parent: Tsok
created_at: '2022-03-01T01:34:05.453459'
last_modified_at: '2022-03-01T01:34:05.453462'
